### ISSUE TITLE
TypeError: Cannot call method 'collection' of null

### ISSUE THREAD

**Issue by agentmusic** [brendannee/node-gtfs#23]
I followed the tutorial and got an error in this line:

node ./scripts/download
Starting caltrain
caltrain: Download successful

/Users/myself/Dropbox/Projekte/Departures/node-gtfs/scripts/download.js:193
        db.collection(GTFSFile.collection, function(e, collection){
           ^
TypeError: Cannot call method 'collection' of null
    at /Users/myself/Dropbox/Projekte/Departures/node-gtfs/scripts/download.js:193:12

Any help is appreciated.

**Comment by agentmusic** [comment]
The MongoDB was missing

**Comment by brendannee** [comment]
I updated the readme to include this step.  Feel free to add more details to the readme if there is other information that would be useful>

https://github.com/brendannee/node-gtfs/commit/4f14ee19b90df4007929ddeb07902267aa8004be
