### ISSUE TITLE
Separate gtfs and node-gtfs-exampleapp

### ISSUE THREAD

**Issue by youtux** [brendannee/node-gtfs#26]
I would like to propose you to separate the `gtfs` lib and the example app in two different github repositories, so that there is a clear distinction between the two, and one can simply deploy the example app without the need to download the library.

The way they are packaged now is counterintuitive for me :).

**Comment by brendannee** [comment]
Hmm, interesting idea.  I'd be interested to hear from others if that makes sense - lots of projects include example implementations within the same repo, and maybe there is a way to keep it in the same repo but make it more intuitive.

**Comment by youtux** [comment]
Well, to make a point in my favour (😅), it would be great to keep the example app I have deployed in sync with the version on the repo. Right now it is not possible for me, since I just downloaded the zip and pushed to Heroku, and I need to manually apply any modification you make on the example app.
Also, I have added an exposed API (the one that uses the new getRoutesByStop), and I would like to share with you by making a PR.

Do you think it would be possible to make the example app (which is not just an example, but a good and working implementation of the web service) a git submodule of this library, so that you can still keep a reference to the example in the main library?

**Comment by brendannee** [comment]
I just pushed an update that split out a new and improved sample app:

https://github.com/brendannee/gtfs-to-html
