### ISSUE TITLE
gtfs: getStopsByRoute taking forever to execute

### ISSUE THREAD

**Issue by youtux** [brendannee/node-gtfs#34]
Hi, I have some troubles with the `getStopsByRoute` function in the `lib/gtfs.js` module.
Currently it takes about 20 seconds in my deployment to execute (heroku app + mongolab db). I think this is caused by the inner function `getTrips`.

I cannot understand why you got in so much troubles by sampling the population just to get the list of trips for a given route. Of course I am missing something, but I would like to understand what.

Just for the sake of comparison, you can find at https://github.com/youtux/node-gtfs/commit/e26cf655e83f640e0f38ad050136135d2afa5e92 a version I came up with which make the same query last 4 seconds instead of 20.

**Comment by brendannee** [comment]
Thanks for opening this issue - I belatedly took a look at your branch and it seems to be an improvement over the sampling - I merged this into master and will review it.
