### ISSUE TITLE
getStops and getTripsByRouteAndDirection bug

### ISSUE THREAD

**Issue by Maregas** [brendannee/node-gtfs#39]
Hi, I need to use **getTripsByRouteAndDirection** and **getStops** function in the **lib/gtfs.js**. When I use them, i get a empty tab. Can you fix this or explain me why I have this issue ?
(I test it with some GTFS, it works only when there is wheelchair_boarding for import stops.txt in the db ?).

**Comment by brendannee** [comment]
Did you figure this out?

**Comment by Maregas** [comment]
yep, it was because my stops.txt didn't contain a "wheelchair_boarding" column and my trips.txt didn't had a "trip_headsign" column.

**Comment by brendannee** [comment]
I updated node-gtfs to include the 'wheelchair_boarding' column - thanks for the heads up.
