### ISSUE TITLE
Variable amount of shapes in db collection

### ISSUE THREAD

**Issue by adampitchie** [brendannee/node-gtfs#47]
It's me again! I stumbled across another issue that I haven't been able to fix.

Some route shape_pt_sequences are either being omitted, or are being added to a different one. I consulted with somebody on this, and they said it's most likely due to a callback not finishing before another async request begins.

This issue only happens on certain datasets, such as `bay-area-rapid-transit`, and not on others, such as `bloomington-transit`. I verified this by cross-referencing the shapes.txt for the files, and then the db.shapes.find() method in mongo.

I didn't check all the datasets that seem to be returning properly to see if all shape_pt_sequences returned correctly.

Here are my results:

## **Proper results**

**`bloomington-transit`**:
from shapes.txt:
`shape_id,shape_pt_lat,shape_pt_lon,shape_pt_sequence`
`1930,39.15466,-86.49328,`**143** (zero indexed, so proper number)

mongoDB query:
`> db.shapes.find({agency_key: 'bloomington-transit', shape_id: '1930'}).count()`
**144**

## **Dataset variation results**

`bay-area-rapid-transit`:

from shapes.txt:
`shape_id,shape_pt_lat,shape_pt_lon,shape_pt_sequence`
`01_shp,37.599782,-122.386655,`**2379**

mongoDB query:
`> db.shapes.find({agency_key: 'bay-area-rapid-transit', shape_id: '01_shp'}).count()`
**2370**

## **Variation within same dataset**

`ac-transit`:

from shapes.txt:
`shape_id,shape_pt_sequence,shape_pt_lat,shape_pt_lon`
Z0048,250198,37.790022,-122.393717 -> Counted manual and has **531** entries

mongoDB query:
`> db.shapes.find({agency_key: 'ac-transit', shape_id: 'Z0048'}).count()`
**531**

--------

from shapes.txt:
`shape_id,shape_pt_sequence,shape_pt_lat,shape_pt_lon`
`10013,680014,37.696816,-122.125840` -> Counted manually and has **730** entries

mongoDB query:
`> db.shapes.find({agency_key: 'ac-transit', shape_id: '10013'}).count()`
**727**

So, as you can see, something is up here, but I don't know what exactly. Thanks in advance!

**Comment by vespakoen** [comment]
Hey Adam,

I am the guy you consulted with, As I was curious myself what was really going on here, I just downloaded the latest version to try it out myself.

I got the latest feed from here: http://transitfeeds.com/p/bart/58 (from 10 march 2016)

Then imported the files with the download.js script and got the same incorrect amount of shapes.

I then extracted the zip and counted the lines that have `01_shp` in it:

```
➜  node-gtfs (master) ✗ cat data/bay-area-rapid-transfer/shapes.txt | grep 01_shp | wc -l
2370
```

As you can see, the data simply has some gaps, so the import script is working fine!

**Comment by adampitchie** [comment]
Ah, great! Thanks Koen for looking into this! You rock!
