### ISSUE TITLE
MTA Import Error

### ISSUE THREAD

**Issue by adampitchie** [brendannee/node-gtfs#49]
Hey guys,

I've been trying to import MTA data, and there are different GTFS files for different regions of the city that are under the same agency with the same agency_key. When I try to import these files, basically the datasets write over the previous ones.

Has anybody tried import MTA data with success?

**Comment by adampitchie** [comment]
I'm wondering if there isn't a fix for this, if I'm just going to have to join all the files together into one massive GTFS set.

**Comment by brendannee** [comment]
I could add a flag on import that would indicate not to erase the previous
import with the same agency key. Would that be useful?

**Comment by adampitchie** [comment]
Yea that would be! But what about when I refresh datasets? Should I just toggle that flag?

Thanks!

**Comment by brendannee** [comment]
Yes, you'd have to exclude the flag when you want to refresh. Can you think
of a better way to solve this issue?

**Comment by adampitchie** [comment]
No not really, unless you could include a CLI flag to specify if it's a refresh or loading new data.

**Comment by brendannee** [comment]
I just pushed an update that has a CLI flag to skip deleting any existing data with the same agency key:

https://github.com/brendannee/node-gtfs#run-the-download-script

Try it out and let me know what you think.

**Comment by adampitchie** [comment]
Tried it out and it works well! Thanks!

**Comment by adampitchie** [comment]
I came across an error. When using this flag the agency_center doesn't calculate correctly, and I get random MTA routes when I search use getRoutesByDistance().

For instance, /api/routesNearby/37.596171/-122.070853/5, returns a lot of ac-transit and bart, and some (not all) MTA routes.

Any ideas for a fix for this?
