### ISSUE TITLE
[Feature Request]: Batch Endpoint for Agency

### ISSUE THREAD

**Issue by adampitchie** [brendannee/node-gtfs#52]
I was wondering if it'd be possible to add a batch endpoint so I could cache all the information client side? I would implement this myself, but I don't know node.js yet! How difficult would this be?

**Comment by brendannee** [comment]
I think caching is something you specifc application should handle, not this package. The main focus of this package is in downloading GTFS and pushing it into a database and providing some endpoints for querying that database.

Can you give more details on your app and why client side caching would be useful?

**Comment by adampitchie** [comment]
Okay, it was worth asking!
