### ISSUE TITLE
Is the distanceInRadians calculation correct?

### ISSUE THREAD

**Issue by melisoner2006** [brendannee/node-gtfs#54]
I am looking at the source code of  `findXXXbyDistance` functions and the distance in radians is found with the following line:

    var radiusInDegrees = Math.round(radius / 69 * 100000) / 100000;

Assuming Radius is the radius of the area to be searched and not the Earth's radius;  Where is the number 69 coming from? I tried to come up with the number but I simply couldn't. Do you mind giving some insight please?

Thanks

**Comment by brendannee** [comment]
Great question.

Mongodb requires a distance in degrees and we have miles so it is:

0.621371 miles/km * 111.320 km/degree  ~= 69.

I pushed an update to the code to make this mode clear. https://github.com/brendannee/node-gtfs/commit/94d582dbebb33ecde411dd5a21f5e023b722b6d3

Check it out and let me know if you have any suggestions on how to improve.
