### ISSUE TITLE
very slow queries getRoutesByStop and getStopsByRoute

### ISSUE THREAD

**Issue by rszczypka** [brendannee/node-gtfs#57]
Hi, I really like this package however I'm noticing that this two queries run very very slow like almost a minute: `getRoutesByStop` and `getStopsByRoute`.

I have 1381 stops and 87 routes in my mongodb.

At application load I have my 'From' combo box filled with all available stops and it gets them quick enough (1.7s).
Then on 'From' blur I'm calling a function to first getRoutesByStop to receive all routes that serves the 'From' stop and then on each route I'm calling getStopsByRoute to receive final list of 'To' stops that you can get to directly from the 'From' stop. This gets (1.5 - 2 minutes)

I'm getting the data eventually but it's extremely slow.

Any suggestions on how to improve it?

**Comment by rszczypka** [comment]
I'm really sorry. 
`parseInt(stopID)` fixed the problem. My bad. Time to go to bed.

**Comment by brendannee** [comment]
Any suggestions on how we can document this or improve it so future developers don't run into this issue?

**Comment by rszczypka** [comment]
Now, when I think about it in the `stops` collection the `stop_id` field is `string` and not `int` but for some reason when I used `int stop_id` as the param for `getRoutesByStop: function(agency_key, stop_id, cb)` it got me the results fast.
