### ISSUE TITLE
How do I get all stops per agency_key?

### ISSUE THREAD

**Issue by rszczypka** [brendannee/node-gtfs#58]
Is there a way to get all stops per agency_key?

I added a new method but not sure if I need it:
```
/*
   * Returns an array of all stops
   */
  getAllStops: function(agency_key, cb) {
   
    Stop.find({
      agency_key: agency_key      
    }, cb).sort({stop_name: 1});
  }
```

**Comment by brendannee** [comment]
I just pushed version 0.4.6 that allows you to get all stops by agency key - use `getStops` with no `stop_ids` specified.
