### ISSUE TITLE
getTripsByRouteAndDirection error

### ISSUE THREAD

**Issue by sebkim** [brendannee/node-gtfs#59]
getTripsByRouteAndDirection function has an issue.

```
getTripsByRouteAndDirection: function(agency_key, route_id, direction_id, service_ids, cb) {
    var query = {
      agency_key: agency_key,
      route_id: route_id,
      direction_id: direction_id
    };
    // if (__.contains([0, 1], direction_id)) {
    //   query.direction_id = direction_id;
    // } else {
    //   query.direction_id = {
    //     $nin: [0, 1]
    //   };
    // }

    if (service_ids && service_ids.length) {
      query.service_id = {
        $in: service_ids
      };
    }
    Trip.find(query, cb);
  },
```

When I modify like above, it works.

**Comment by brendannee** [comment]
Can you tell me which agency you were using this with that wasn't working?  Do you have an example of the error that was happening?

**Comment by sebkim** [comment]
i used caltrain gtfs.
I have no example now.

On Tuesday, May 31, 2016, Brendan Nee <notifications@github.com> wrote:

> Can you tell me which agency you were using this with that wasn't working?
> Do you have an example of the error that was happening?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/brendannee/node-gtfs/issues/59#issuecomment-222831948>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AMc0bIjF_tAbG1-0yj-psIw2G0zYd_JZks5qHKzqgaJpZM4IpgvU>
> .
>


-- 
Best,
Sebo

**Comment by ericmikkelsen** [comment]
I'm having that issue with the CTA

**Comment by brendannee** [comment]
I pushed an update in 0.6.0 that may have resolved this issue - check it out and please reopen this if you still get the same problem.
