### ISSUE TITLE
skipping shapes.txt?

### ISSUE THREAD

**Issue by rjayako** [brendannee/node-gtfs#61]
Hey guys, I'm wondering if it's possible to skip the shapes.txt import and download all together. It always causes my server to slow down and hang and I don't really need this file for my project. Just wondering if this is possible.

Thanks.

**Comment by brendannee** [comment]
Great idea - I just pushed an update 0.4.7 that has this feature. 

You an define which files to exclude in config.js.

**Comment by rjayako** [comment]
@brendannee that's amazing, thank you!
