### ISSUE TITLE
Throws [Error: Number of columns on line xxx does not match header] for the empty line at the end of the file.

### ISSUE THREAD

**Issue by melisoner2006** [brendannee/node-gtfs#62]
I was uploading this data set (url: http://www.bart.gov/dev/schedules/google_transit.zip) with version 0.4.5. It threw the followinf error when processing transfers.txt.

`[Error: Number of columns on line 8 does not match header]`

I checked the file and saw line 8 is an empty line at the end of the file.

I found this issue also appears in version 0.1.1

I was uploading san-francisco-municipal-transportation-agency (with version 0.1.1 and 0.1.0) and it threw

```
san-francisco-municipal-transportation-agency: Importing data - routes
san-francisco-municipal-transportation-agency: Importing data - shapes
[Error: Number of columns on line 104007 does not match header]
```

Again, line 104007 appeared to be an empty line at the end of the file shapes.txt

![screen shot 2016-07-26 at 11 56 47 am](https://cloud.githubusercontent.com/assets/3477494/17145429/1aa380cc-5328-11e6-8d29-9d666063da9a.png)

**Comment by brendannee** [comment]
This issue should be resolved with the latest version of node-gtfs. Please reopen if you experience the same issue.
