### ISSUE TITLE
Querying just doesn't work.

### ISSUE THREAD

**Issue by ghost** [brendannee/node-gtfs#67]
http://pastebin.com/rKHQJ0Bp

I have been trying to get this working for hours now. It just doesn't print anything to the console on lines 75 and 76.

**Comment by brendannee** [comment]
I was able to get your code to print stops when loading

http://localhost:3000/getstop?lat=59.4519345122069&lng=24.5839149880253

Can you paste what output you get when loading that route in your browser?

**Comment by SuperSaltyGamer** [comment]
(node:8468) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
Got (404)

**Comment by brendannee** [comment]
Can you post your whole project as a git repo including the package.json? Its possible that this issue is caused by how the various npm packages were installed.

Doing a fresh npm install based on a package.json for this project might solve it.

**Comment by SuperSaltyGamer** [comment]
You have the whole app.js. I don't have any other server-side files and none of the clientside files are completely separate.

Here's the package.json:
http://pastebin.com/9VH36Z6Z

In overrides.txt I have:
[stop_id]:Lorem Ipsum

I launch the app from an elevated command prompt.
Version of NodeJS: 7.2.1
Version of MongoDB: 3.2

**Comment by brendannee** [comment]
Try specifying mongoose version 4.7.0 in your package.json and deleting then reinstalling all node_modules. I suspect there is an issue with mongoose promises and the fact that node-gtfs specifies a version that is different than your package.json. Alternatively, you could remove mongoose from package.json which will force your project to rely on the version specified by node-gtfs.

I'm going to work on making this not happen - but let me know if that solves your issue.

**Comment by brendannee** [comment]
You could make mongoose 4.7.x a peerDependency of your project, so it will just use the version specified in node-gtfs if you want.

**Comment by lpolaright** [comment]
SuperSaltyGamer, it seems like you are printing "Got (404)" in two cases:
1. when "lat" or "lon" isNaN
2. in the end of the "app.get('/getstop'..."

First of all, I'd recommend renaming the error message, because maybe "lat" or "lon" are empty due to req.query not working.

Another something I noticed:
gtfs.getStopsByDistance - is async if I remember correctly.
It could be that you are "res.status(404).send();" before "gtfs.getStopsByDistance" finishes running - which might result in sending a response before you finish querying.

Try moving lines 79, 80 to after line 76.

Let us know 👍

**Comment by SuperSaltyGamer** [comment]
The first print is actually "Got (400)".
After moving 79 and 80 to 76 it still didn't work.
While keeping the lines on 76, after changing mongoose to version 4.7.0 in package.json and reinstalling all modules it gave this error http://i.imgur.com/H6m3OJE.png.
Then when I changed the mongoose dependency to a peerDependency with the version 4.7.x and reinstalled it worked.

**Comment by brendannee** [comment]
Glad the peer dependency method worked.

I'm not sure if I should make mongoose a peerDependency of node-gtfs to
avoid this issue. I think if it's a peer dependency it won't get installed
when you install node-gtfs globally, which makes an extra step for those
who want to use this as a command line tool.
